<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\FormType;

class FormTypeSeeder extends Seeder
{
    public function run()
    {
        if (FormType::where('type', 'MainForm')->exists()) {
            return;
        }

        FormType::create([
            'type'      => 'MainForm',
            'addionals' => [
                'fields' => [
                    ["name" => "spec_circumstance_indicator_code", "label" => "Код обстоятельства"],
                    ["name" => "spec_circumstance_indicator_name", "label" => "Название обстоятельства"],
                    ["name" => "total_gross_mass_kg", "label" => "Общая масса груза (кг)"],
                    ["name" => "unique_consignment_trsp_refer_no", "label" => "Уникальный номер перевозки"],
                    ["name" => "notify_party_code", "label" => "Код уведомляемой стороны"],
                    ["name" => "notify_party_name", "label" => "Название уведомляемой стороны"],
                    ["name" => "arrival_on_customs_territory_date", "label" => "Дата прибытия на таможню"],
                    ["name" => "arrival_on_customs_territory_time", "label" => "Время прибытия на таможню"],
                    ["name" => "office_transit_code_1", "label" => "Код офиса транзита 1"],
                    ["name" => "country_transit_code_1", "label" => "Код страны транзита 1"],
                    ["name" => "date_transit_1", "label" => "Дата транзита 1"],
                    ["name" => "office_transit_code_2", "label" => "Код офиса транзита 2"],
                    ["name" => "country_transit_code_2", "label" => "Код страны транзита 2"],
                    ["name" => "date_transit_2", "label" => "Дата транзита 2"],
                    ["name" => "office_transit_code_3", "label" => "Код офиса транзита 3"],
                    ["name" => "country_transit_code_3", "label" => "Код страны транзита 3"],
                    ["name" => "date_transit_3", "label" => "Дата транзита 3"],
                    ["name" => "office_transit_code_4", "label" => "Код офиса транзита 4"],
                    ["name" => "country_transit_code_4", "label" => "Код страны транзита 4"],
                    ["name" => "date_transit_4", "label" => "Дата транзита 4"],
                    ["name" => "free_text_for_additional_document", "label" => "Дополнительный текст"],
                    ["name" => "sad_flow", "label" => "Sad Flow"],
                    ["name" => "number_of_the_form", "label" => "Номер формы"],
                    ["name" => "total_number_of_forms", "label" => "Общее число форм"],
                    ["name" => "number_of_loading_lists", "label" => "Число загрузочных листов"],
                    ["name" => "total_number_of_items", "label" => "Общее число позиций"],
                    ["name" => "total_number_of_packages", "label" => "Общее число упаковок"],
                    ["name" => "total_number_of_consignments", "label" => "Общее число грузовых мест"],
                    ["name" => "customs_clearance_office_code", "label" => "Код таможни оформления"],
                    ["name" => "customs_departure_office_code", "label" => "Код таможни отправления"],
                    ["name" => "customs_office_of_destination_code", "label" => "Код таможни назначения"],
                    ["name" => "country_of_cuo_of_destination", "label" => "Страна назначения (CUO)"],
                    ["name" => "type_of_declaration", "label" => "Тип декларации"],
                    ["name" => "declaration_gen_procedure_code", "label" => "Код процедуры декларации"],
                    ["name" => "type_of_transit_document2", "label" => "Тип документа транзита 2"],
                    ["name" => "type_of_transit_document3", "label" => "Тип документа транзита 3"],
                    ["name" => "manifest_reference_number", "label" => "Номер манифеста"],
                    ["name" => "external_flag", "label" => "Внешний флаг"],
                    ["name" => "non_conform_flag", "label" => "Флаг несоответствия"],
                    ["name" => "examination_of_seals", "label" => "Осмотр пломб"],
                    ["name" => "arrival_planned_date", "label" => "Плановая дата прибытия"],
                    ["name" => "serial_number_from_declaration", "label" => "Серийный номер из декларации"],
                    ["name" => "number_from_declaration", "label" => "Номер из декларации"],
                    ["name" => "date_from_declaration", "label" => "Дата из декларации"],
                    ["name" => "assessment_serial_number", "label" => "Серийный номер оценки"],
                    ["name" => "assessment_number", "label" => "Номер оценки"],
                    ["name" => "assessment_date", "label" => "Дата оценки"],
                    ["name" => "termination_date", "label" => "Дата завершения"],
                    ["name" => "invoice_amount", "label" => "Сумма инвойса"],
                    ["name" => "invoice_currency_code", "label" => "Валюта инвойса"],
                    ["name" => "exporter_code", "label" => "Код экспортёра"],
                    ["name" => "exporter_name", "label" => "Название экспортёра"],
                    ["name" => "exporter_ctyCod", "label" => "Код страны экспортёра"],
                    ["name" => "exporter_regDsc", "label" => "Описание регистрации экспортёра"],
                    ["name" => "exporter_regCod", "label" => "Код регистрации экспортёра"],
                    ["name" => "exporter_catCod", "label" => "Категория экспортёра"],
                    ["name" => "exporter_street", "label" => "Улица экспортёра"],
                    ["name" => "exporter_city", "label" => "Город экспортёра"],
                    ["name" => "consignee_code", "label" => "Код грузополучателя"],
                    ["name" => "consignee_name", "label" => "Название грузополучателя"],
                    ["name" => "consignee_ctyCod", "label" => "Код страны грузополучателя"],
                    ["name" => "consignee_regDsc", "label" => "Описание регистрации грузополучателя"],
                    ["name" => "consignee_regCod", "label" => "Код регистрации грузополучателя"],
                    ["name" => "consignee_catCod", "label" => "Категория грузополучателя"],
                    ["name" => "consignee_street", "label" => "Улица грузополучателя"],
                    ["name" => "consignee_city", "label" => "Город грузополучателя"],
                    ["name" => "delivery_party_code", "label" => "Код грузоотправителя/перевозчика"],
                    ["name" => "carrier_name", "label" => "Название перевозчика"],
                    ["name" => "carrier_ctyCod", "label" => "Код страны перевозчика"],
                    ["name" => "carrier_regDsc", "label" => "Описание регистрации перевозчика"],
                    ["name" => "carrier_regCod", "label" => "Код регистрации перевозчика"],
                    ["name" => "carrier_catCod", "label" => "Категория перевозчика"],
                    ["name" => "carrier_street", "label" => "Улица перевозчика"],
                    ["name" => "carrier_city", "label" => "Город перевозчика"],
                    ["name" => "driver", "label" => "Водитель"],
                    ["name" => "declarant_code", "label" => "Код декларанта"],
                    ["name" => "declarant_name", "label" => "Название декларанта"],
                    ["name" => "declarant_ctyCod", "label" => "Код страны декларанта"],
                    ["name" => "declarant_regDsc", "label" => "Описание регистрации декларанта"],
                    ["name" => "declarant_regCod", "label" => "Код регистрации декларанта"],
                    ["name" => "declarant_catCod", "label" => "Категория декларанта"],
                    ["name" => "declarant_street", "label" => "Улица декларанта"],
                    ["name" => "declarant_city", "label" => "Город декларанта"],
                    ["name" => "declarant_representative", "label" => "Представитель декларанта"],
                    ["name" => "reference_year", "label" => "Год справки"],
                    ["name" => "reference_number", "label" => "Номер справки"],
                    ["name" => "export_country_code", "label" => "Код страны экспорта"],
                    ["name" => "destination_country_code", "label" => "Код страны назначения"],
                    ["name" => "transport_border_mode", "label" => "Режим границы (транспорт)"],
                    ["name" => "container_flag", "label" => "Флаг контейнера"],
                    ["name" => "container_flag_additional", "label" => "Дополнительный флаг контейнера"],
                    ["name" => "place_of_loading_code", "label" => "Код места загрузки"],
                    ["name" => "guarantee_code", "label" => "Код гарантии"],
                    ["name" => "guarantee_amount", "label" => "Сумма гарантии"],
                    ["name" => "guarantee_country", "label" => "Страна гарантии"],
                    ["name" => "mog", "label" => "MOG"],
                    ["name" => "incident1_transport_identity", "label" => "Идентификатор транспорта (Инцидент 1)"],
                    ["name" => "incident1_transport_nationality", "label" => "Национальность транспорта (Инцидент 1)"],
                    ["name" => "incident1_container_flag", "label" => "Флаг контейнера (Инцидент 1)"],
                    ["name" => "incident1_container_identity", "label" => "Идентификатор контейнера (Инцидент 1)"],
                    ["name" => "incident1_seals_number", "label" => "Количество пломб (Инцидент 1)"],
                    ["name" => "incident1_seals_identity", "label" => "Идентификатор пломб (Инцидент 1)"],
                    ["name" => "incident1_date", "label" => "Дата инцидента 1"],
                    ["name" => "incident1_place", "label" => "Место инцидента 1"],
                    ["name" => "incident1_country", "label" => "Страна инцидента 1"],
                    ["name" => "incident2_transport_identity", "label" => "Идентификатор транспорта (Инцидент 2)"],
                    ["name" => "incident2_transport_nationality", "label" => "Национальность транспорта (Инцидент 2)"],
                    ["name" => "incident2_container_flag", "label" => "Флаг контейнера (Инцидент 2)"],
                    ["name" => "incident2_container_identity", "label" => "Идентификатор контейнера (Инцидент 2)"],
                    ["name" => "incident2_seals_number", "label" => "Количество пломб (Инцидент 2)"],
                    ["name" => "incident2_seals_identity", "label" => "Идентификатор пломб (Инцидент 2)"],
                    ["name" => "incident2_date", "label" => "Дата инцидента 2"],
                    ["name" => "incident2_place", "label" => "Место инцидента 2"],
                    ["name" => "incident2_country", "label" => "Страна инцидента 2"],
                    ["name" => "transit_principal_code", "label" => "Код принципала (транзит)"],
                    ["name" => "transit_principal_name", "label" => "Название принципала (транзит)"],
                    ["name" => "transit_principal_ctyCod", "label" => "Код страны принципала (транзит)"],
                    ["name" => "transit_principal_regDsc", "label" => "Регистрационное описание принципала (транзит)"],
                    ["name" => "transit_principal_regCod", "label" => "Регистрационный код принципала (транзит)"],
                    ["name" => "transit_principal_catCod", "label" => "Категория принципала (транзит)"],
                    ["name" => "transit_principal_street", "label" => "Улица принципала (транзит)"],
                    ["name" => "transit_principal_city", "label" => "Город принципала (транзит)"],
                    ["name" => "transit_principal_representative", "label" => "Представитель принципала (транзит)"],
                    ["name" => "transit_signature_place", "label" => "Место подписи (транзит)"],
                    ["name" => "transit_signature_date", "label" => "Дата подписи (транзит)"],
                    ["name" => "transit_seals_number", "label" => "Количество пломб (транзит)"],
                    ["name" => "transit_seals_type", "label" => "Тип пломб (транзит)"],
                    ["name" => "transit_seals_identity", "label" => "Идентификатор пломб (транзит)"],
                    ["name" => "transit_incidents", "label" => "Инциденты (транзит)"],
                    ["name" => "transit_result_of_control", "label" => "Результат контроля (транзит)"],
                    ["name" => "transit_time_limit", "label" => "Срок (транзит)"],
                    ["name" => "image_ni1", "label" => "Изображение NI1"],
                    ["name" => "image_ni2", "label" => "Изображение NI2"],
                    ["name" => "attach_doc1", "label" => "Прикрепленный документ 1"],
                    ["name" => "attach_doc2", "label" => "Прикрепленный документ 2"],
                    ["name" => "attach_doc3", "label" => "Прикрепленный документ 3"],
                    ["name" => "attach_doc4", "label" => "Прикрепленный документ 4"],
                    ["name" => "driver1", "label" => "Изображение водителя 1"],
                    ["name" => "driver2", "label" => "Изображение водителя 2"],
                    ["name" => "seal", "label" => "Изображение пломбы"],
                    ["name" => "item_consignment_number", "label" => "Номер грузовой партии"],
                    ["name" => "item_is_new_consignment", "label" => "Новая грузовая партия"],
                    ["name" => "item_consignee_code", "label" => "Код грузополучателя (Item)"],
                    ["name" => "item_consignee_name", "label" => "Название грузополучателя (Item)"],
                    ["name" => "item_consignee_ctyCod", "label" => "Код страны грузополучателя (Item)"],
                    ["name" => "item_consignee_regDsc", "label" => "Регистрационное описание грузополучателя (Item)"],
                    ["name" => "item_consignee_regCod", "label" => "Регистрационный код грузополучателя (Item)"],
                    ["name" => "item_consignee_catCod", "label" => "Категория грузополучателя (Item)"],
                    ["name" => "item_consignee_street", "label" => "Улица грузополучателя (Item)"],
                    ["name" => "item_consignee_city", "label" => "Город грузополучателя (Item)"],
                    ["name" => "item_exporter_code", "label" => "Код экспортёра (Item)"],
                    ["name" => "item_exporter_name", "label" => "Название экспортёра (Item)"],
                    ["name" => "item_exporter_ctyCod", "label" => "Код страны экспортёра (Item)"],
                    ["name" => "item_exporter_regDsc", "label" => "Регистрационное описание экспортёра (Item)"],
                    ["name" => "item_exporter_regCod", "label" => "Регистрационный код экспортёра (Item)"],
                    ["name" => "item_exporter_catCod", "label" => "Категория экспортёра (Item)"],
                    ["name" => "item_exporter_street", "label" => "Улица экспортёра (Item)"],
                    ["name" => "item_exporter_city", "label" => "Город экспортёра (Item)"],
                    ["name" => "dangerous_goods_code", "label" => "Код опасного груза"],
                    ["name" => "dangerous_goods_name", "label" => "Название опасного груза"],
                    ["name" => "packages_number_of_packages", "label" => "Количество упаковок (Item)"],
                    ["name" => "packages_marks1_of_packages", "label" => "Маркировка упаковок (Item)"],
                    ["name" => "packages_kind_of_packages_code", "label" => "Код типа упаковки (Item)"],
                    ["name" => "tarification_commodity_code", "label" => "Код товара (HS)"],
                    ["name" => "tarification_unit_of_measure_code", "label" => "Код единицы измерения (Item)"],
                    ["name" => "tarification_quantity", "label" => "Количество (Item)"],
                    ["name" => "tarification_item_currency_code", "label" => "Валюта товара (Item)"],
                    ["name" => "tarification_item_price", "label" => "Цена товара (Item)"],
                    ["name" => "attached_document_code_1", "label" => "Код прикрепленного документа 1"],
                    ["name" => "attached_document_reference_1", "label" => "Ссылка прикрепленного документа 1"],
                    ["name" => "attached_document_date_1", "label" => "Дата прикрепленного документа 1"],
                    ["name" => "attached_document_code_2", "label" => "Код прикрепленного документа 2"],
                    ["name" => "attached_document_reference_2", "label" => "Ссылка прикрепленного документа 2"],
                    ["name" => "attached_document_date_2", "label" => "Дата прикрепленного документа 2"],
                    ["name" => "attached_document_code_3", "label" => "Код прикрепленного документа 3"],
                    ["name" => "attached_document_reference_3", "label" => "Ссылка прикрепленного документа 3"],
                    ["name" => "attached_document_date_3", "label" => "Дата прикрепленного документа 3"],
                    ["name" => "goods_container_1", "label" => "Контейнер 1 (описание товаров)"],
                    ["name" => "goods_container_2", "label" => "Контейнер 2 (описание товаров)"],
                    ["name" => "goods_description_of_goods", "label" => "Описание товаров (Item)"],
                    ["name" => "goods_commercial_description", "label" => "Коммерческое описание (Item)"],
                    ["name" => "previous_doc_cod", "label" => "Код предыдущего документа (Item)"],
                    ["name" => "previous_doc_nbr", "label" => "Номер предыдущего документа (Item)"],
                    ["name" => "previous_doc_dat", "label" => "Дата предыдущего документа (Item)"],
                    ["name" => "previous_doc_man", "label" => "PrevDocMan (Item)"],
                    ["name" => "previous_doc_national", "label" => "PrevDocNational (Item)"],
                    ["name" => "valuation_gross_weight_itm", "label" => "Вес брутто (Item)"],
                    ["name" => "valuation_net_weight_itm", "label" => "Вес нетто (Item)"],
                    ["name" => "entry_office_code", "label" => "Код входного офиса"],
                    ["name" => "transport_multiple_tpt_flg", "label" => "Флаг транспортного средства (множественный)"],
                    ["name" => "transport_multiple_tpt_trk", "label" => "Номер транспортного средства (множественный)"],
                    ["name" => "transport_multiple_tpt_trl", "label" => "Номер прицепа (множественный)"],
                    ["name" => "transport_multiple_tpt_cty", "label" => "Код страны транспортного средства (множественный)"],
                ]
            ],
            'created_by' => 'system'
        ]);
    }
}
